const $=id=>document.getElementById(id); let token=localStorage.getItem('medilink_token');
const nomes={inicio:'Início',novo:'Novo agendamento',consultas:'Meus agendamentos',avisos:'Notificações'};
function iniciar(){const logado=!!token;$('login').hidden=logado;$('painel').hidden=!logado;$('sidebar').hidden=!logado;$('topbar').hidden=!logado;if(logado){abrir('inicio');atualizar()}}
async function entrar(){ $('erro').textContent=''; try{const r=await fetch('/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:$('email').value.trim(),senha:$('senha').value})});const d=await r.json();if(!r.ok){$('erro').textContent=d.erro;return}token=d.token;localStorage.setItem('medilink_token',token);iniciar();toast('Login realizado com sucesso!')}catch(e){$('erro').textContent='Não foi possível conectar ao servidor.'}}
$('logout').onclick=()=>{localStorage.removeItem('medilink_token');token=null;iniciar()};
document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>abrir(b.dataset.view));
function abrir(id){document.querySelectorAll('.view').forEach(v=>v.hidden=v.id!==id);document.querySelectorAll('.nav').forEach(n=>n.classList.toggle('active',n.dataset.view===id));$('titulo').textContent=nomes[id];if(id!=='novo')atualizar()}
async function agendar(){const paciente=$('paciente').value.trim(),data=$('data').value,hora=$('hora').value;if(!paciente||!data||!hora)return toast('Preencha paciente, data e horário.');const body={paciente,especialidade:$('especialidade').value,profissional:$('profissional').value,data,hora};const r=await fetch('/api/agendamentos',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});if(!r.ok)return toast('Não foi possível agendar.');$('paciente').value='';$('data').value='';$('hora').value='';toast('Consulta agendada com sucesso!');abrir('consultas')}
async function excluir(id){if(!confirm('Deseja cancelar este agendamento?'))return;await fetch('/api/agendamentos/'+id,{method:'DELETE'});toast('Agendamento cancelado.');atualizar()}
function formatarData(s){const [a,m,d]=s.split('-');return `${d}/${m}/${a}`}
function card(a){const [y,m,d]=a.data.split('-'),meses=['JAN','FEV','MAR','ABR','MAI','JUN','JUL','AGO','SET','OUT','NOV','DEZ'];return `<div class="appointment"><div class="datebox"><b>${d}</b><small>${meses[+m-1]}</small></div><div class="info"><b>${a.especialidade}</b><span>${a.paciente} · ${a.profissional||'Profissional MediLink'} · ${a.hora}</span></div><span class="status">Confirmado</span><button class="danger" onclick="excluir(${a.id})">Cancelar</button></div>`}
async function atualizar(){try{const a=await (await fetch('/api/agendamentos')).json(),n=await (await fetch('/api/notificacoes')).json();$('total').textContent=a.length;$('proximos').textContent=a.length;$('totalNotif').textContent=n.length;$('badge').textContent=n.length;$('badge').style.display=n.length?'inline':'none';const vazio='<div class="empty"><strong>Nenhum agendamento</strong>Crie seu primeiro agendamento para ele aparecer aqui.</div>';$('lista').innerHTML=a.length?a.map(card).join(''):vazio;$('resumoLista').innerHTML=a.length?a.slice(0,3).map(card).join(''):vazio;$('notifs').innerHTML=n.length?n.slice().reverse().map(x=>`<div class="notif"><div class="notif-icon">✓</div><div><b>${x.mensagem}</b><span>Serviço de Notificações · MediLink</span></div></div>`).join(''):'<div class="empty"><strong>Nenhuma notificação</strong>As confirmações aparecerão aqui.</div>'}catch(e){console.error(e)}}
function toast(msg){const t=$('toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2600)}
const hoje=new Date();$('data').min=hoje.toISOString().split('T')[0];iniciar();
